sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-121
env:
  global:
    -
      # LTD_AWS_ID
      secure: C4oxnNIq22cpHsotJCUeIrGF1wDnH63w7YQBjg+x53/W6pqOR+zNqHN0cSh8rOwh+jTU6z5otCz5idmZChXivIDFM577H8pEOkgrsJ1PeDTMukphWukvbB3X4+VMC/otpu3x8bo3p6pfCsb9WauoVfeCT8c/RhjOtU2ro7UDYIgVw7iGs4z7tc3wNjoXLZbqMeOHFn3fM3K3A38OSw9sDPISlbRct/TbXcihxoqVyeyPNLoTjLYyW65gE/rDryVube78ofXX6DMA7Bt2iEeNXRZKTOw737qxLIMu5W0VfE9CZIAqWY10Aca1W3bsG7wrMKGxezISM4bFxSft/tkUvXSVR/mRxpdrz97/jR39LJzXLLTYtTI5QwCk9JEC4rbOIynOgcTBYRwpas5Lfo2NPSv6NYs9oqBaAAjgHh4i70ER0QUcpNCNiSx1i6Wl0J7H0GJsSr6q5AseMeYbmoZpTOp26vZE7F5J5LUDJmrdiVbD9edUNU8EQD5ZZEslCOoWZcuQ3mSgR1aouOuoTkQfKS1vIquTYKrJDZkEZgG6pqTO6iFo9ioyLTARb5eikciTasmmQRNRUjtC62NifBU4BOQGyOFHBV81mxgmJ8YgZxTvUpkyo3MLprSSDR9xWhjKyb9WT2kaVKAKHQKSsfp0S+yBHKQI7cWKgz2s6iCpWFs=
    -
      # LTD_AWS_SECRET
      secure: LhlO+V6zoIhr6gUeijrklBBQg3149GJH5is4JvgUSr6gTfCG0NczNQr6ytM3VV71JHjPw77E31WOyr3XW79zcIEhf7qA+5Qc6ula4HdN2um1IOVrZA6r+rBdamP+bCGtpYz8GANDSwD3TaOA01uUIL2gkB1G0pzCMB3BdRHbaE9N2vCgMyRojMitXtzxpAhwwKgtbpUF4O567f8tBsBe9w1/xU0HwUclAS9/kADdN+rp2iKbiCA4IZ7L3TfnZemdpuXzvvtnKZhPpo77Jqbmofa5p9nFp9HaPDk7MEo1D72fxzb43LXr4jLa2PHfOG11G0siZE5Bl2/QkoywCKxguCtH01Kj80I7XMCpVNy4UM2aQfP46bpTJWVULiReS8HKYr9b55s1tGo9l4AkND19LBtVvWYCSXM8yHQc32sSjmMgtqktIvYtObDsCUp8iQPvXzbl4iARx3DaL0wvIb81Bx8WTLe0zQqRVEXkXSjum7lF4ILoSXTLaxLflGxeWWILd3Cce+ugN0RHvUrUN6i1ZDOfZ9qirfXCnyaWg6o6OIXU+27yEoLqUaRMe5bb84al2CWLE18rcrRthFPcwPTSwO7ZtWcZ+wCExFezQlAEdp0FXhE6jtRwALCSpBgVpBXeyzb+4Ix4unqR2Mq82g/WMGaWxfQGhC+GI82eClFK6kk=
    -
      # LTD_USERNAME
      secure: gQQvWM+ein6obYSzRtGEEKV5BhaK2YXDO0L7aZ/LX0Al408uLS+3k3+xL/Cxi64pjxZWlMf02/tytXHfKWT1G1GsYw4zho0QjNLcdMqbhZEhVC2SenUClMu2PadAXtQmf1pkEY1tu7bnzX8Py7+qjZQkumt1MGcB+fjOWd8dM66rPTvo4pJOCJqH/olTW7JcHm2OWE7AnDA0u4DeryIy5ejC0yMfGkvEBqtmzka/h0HqLiT2OkdNv10xcas7y7Aa3A3+Y6paSFh6MBFeypsL8dz7zBvYshNtJ8TR6XKwedp7cWoLJnGx3f1hDiSM9K/NDpUZ8oHXVOwx3HNXxZlnfsy4W+dPfZOqLpM0TQir6kr5sj/v+lOwTWjkDR/ErLncBAEFUJ+4gpo8DMUBP004jSjPxozPRzsZ8emwQgqUnVMR2NlL8sqaqlz8XErD3FGMhhJsOwoO1w9UQc3n4g8lLcCTA2gjnRJ4UyzUd2Z2bAMKUotY6OrCsP7XYxPWqtx2wfLRX+yzaUE6Ahf/154EyVHFxd4XMThoTKhKMfVVcR2cUnb+k6Ztqtn2qgAltCL9sGNMMzEgBJZYpB/Rk8WxOAbufQBKS6lhtYQMUcFGZvRfAqlK8czI6PiRLDbUImN0Xv3SqACWTfZoaskPtwvpAmMyX9ZEJDzp/yu/uUaVUAQ=
    -
      # LTD_PASSWORD
      secure: GiRirUhHedaWT9Sa6JyCjmFfOJmSINkMUAF8OPxoxg2elmLxcZfdLnrHM4QcC07d439PsF/fADIrm87AQ1zbMgIbHUyfwcIH1swQCzv20pDGFajlyPg3sKYtp+T/mh25l2Bx9iEPWjjP43fsPNJmuaTnUCM1D2zfk6mbmJK1OjJiNv73jMDFiQFt3wptoVBzC/DSP9dMxhgkzJsqST/g/BQ9HFJEqmoE5TFZbhCVCHYdqYZvXoOt4eEnZA0MP1NwCSefCJVS2z3Gkeh1/DVi+pAO4TdhAUVcQRfsSOjf4SqiYUdIlCTY+0dS7NP1ld1DtFSZZPc1+m/J9EqyskCsvqqhOGriruIfofUbSTenc+hlOhJRKw8irE5+SJXNt/s/PsvlxxeW2IvfLjOdZhJDjik0DD2pSpzsngcAvODMgX6kfVi7yqUxHS5lG2MXIbPqY4FDL96UPFef+Rf4/RrBAGoPAOxqo+8oTvz0gKZkjFKnzX/7h57c+bpCcfr/uGDhW6PNG5UhUMbHGVlmpEzjMwqNBbFfWTgTtJxg2yUWY6Y6RQDD/fGmlhRq3OSP9fLoLXJIzcycFRJ/jd2oRZuDt4uKLt1zvtmKg962dBtyqYMUrk1OPw0ZoOeEqOycPcTnKUDZhS7xKaBy+eI+nffO63rVrh1ROa1SQkOcC4xN5nE=
